### ISSUE TITLE
Waves in elastic media

### ISSUE THREAD

**Issue by vasily-golubev** [HPCSys-Lab/simwave#54]
Hello,

I am wondering if you have some plans to develop FDTD solver for 2D and 3D full linear elastic equations (isotropic, or maybe VTI/full anisotropic case)? It will be a great help to have a verified open-source solved with a good PML realization.

**Comment by jaimesouza** [comment]
I may recommend the references below:

- Acoustic modeling (general overview)

A. Fichtner, Full seismic waveform modelling and inversion, Springer Sci-ence & Business Media, 2010.

- Sources and receivers

Hicks, G. J. [2002], 'Arbitrary source and receiver positioning in finite-difference schemes using Kaiser windowed sinc functions', Geophysics 67(1), 156–166.

- Numerical stability

Lines, L. R., Slawinski, R. and Bording, R. P. [1999], 'A recipe for stability of finite-difference wave-equation computations', Geophysics 64(3), 967–969.

- PML

Grote, Marcus J., Sim, Imbo [2010], 'Efficient PML for the wave equation'. (https://arxiv.org/abs/1001.0319)
