### ISSUE TITLE
Ultrasound wave propagation 

### ISSUE THREAD

**Issue by Nicko222** [HPCSys-Lab/simwave#57]
Dear @jaimesouza ,
Thanks for your contribution. I would like to know if I can use it in ultrasound wave propagation such as 2.5MHz frequency. If yes, do you have experience in the space model or the computational time. Thanks a lot!

**Comment by joao-bapdm** [comment]
Hi @Nicko222 ,

I understand that, in principle, it is possible to do simulations with very high frequencies and proportionally smaller length scales. In our group however we haven't tried this type of application.
