### ISSUE TITLE
More snapshots.

### ISSUE THREAD

**Issue by Hubert-LEROUX** [HPCSys-Lab/simwave#61]
Hello.

The package is great but I have some difficulties to use it.
The example given on the readme.md generate a solution with only one snapshot. How do I increase the number of snapshots ?
I would like to create a video of the evolution of the wave.

Thanks.

**Comment by jaimesouza** [comment]
Hello Hubert,

Thanks for using simwave and contacting us. 

We appreciate your feedback. 

We are working to create a documentation and improve simwave's functionalities. 

To increase the number of snapshots, you can do as follow:

```
time_model = TimeModel(
    space_model=space_model,
    tf=1.0,
    saving_stride=1
)
```

Set the `saving_stride=1` (or a number higher than 1, if you want to increase the stride). The default `saving_stride=0` means you do not want to save intermediate snapshots.

**Comment by Hubert-LEROUX** [comment]
Thanks.
